import type { Config } from "tailwindcss";

/**
 * Lexi Legal Intelligence — design tokens extracted from
 * Google Stitch project "Lexi AI Legal Workspace" (3906199904898572878).
 * Source: .stitch/project.json (designTheme) + per-screen tailwind.config blobs.
 */
const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#fcf9f8",
        surface: "#fcf9f8",
        "surface-bright": "#fcf9f8",
        "surface-dim": "#dcd9d9",
        "surface-variant": "#e5e2e1",
        "surface-tint": "#3446ee",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f3f2",
        "surface-container": "#f0edec",
        "surface-container-high": "#ebe7e7",
        "surface-container-highest": "#e5e2e1",
        "on-surface": "#1c1b1b",
        "on-background": "#1c1b1b",
        "on-surface-variant": "#454656",
        "inverse-surface": "#313030",
        "inverse-on-surface": "#f3f0ef",
        "inverse-primary": "#bdc2ff",
        outline: "#757687",
        "outline-variant": "#c5c5d9",
        primary: "#1e32df",
        "on-primary": "#ffffff",
        "primary-container": "#3f51f7",
        "on-primary-container": "#e5e5ff",
        "primary-fixed": "#dfe0ff",
        "primary-fixed-dim": "#bdc2ff",
        "on-primary-fixed": "#000866",
        "on-primary-fixed-variant": "#0b24d7",
        secondary: "#5b5f64",
        "on-secondary": "#ffffff",
        "secondary-container": "#dde0e6",
        "on-secondary-container": "#5f6368",
        "secondary-fixed": "#dfe3e8",
        "secondary-fixed-dim": "#c3c7cc",
        "on-secondary-fixed": "#181c20",
        "on-secondary-fixed-variant": "#43474c",
        tertiary: "#005c30",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#007740",
        "on-tertiary-container": "#86ffaf",
        "tertiary-fixed": "#82faab",
        "tertiary-fixed-dim": "#64dd91",
        "on-tertiary-fixed": "#00210e",
        "on-tertiary-fixed-variant": "#00522b",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        margin: "2rem",
        gutter: "1.5rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
      },
      fontFamily: {
        sans: ["var(--font-geist-sans)", "Inter", "system-ui", "sans-serif"],
        display: ["var(--font-geist-sans)", "Inter", "system-ui", "sans-serif"],
        code: ["var(--font-jetbrains-mono)", "monospace"],
        // Stitch token aliases
        "display-hero": ["var(--font-geist-sans)"],
        "display-hero-mobile": ["var(--font-geist-sans)"],
        "headline-lg": ["var(--font-geist-sans)"],
        "headline-lg-mobile": ["var(--font-geist-sans)"],
        "headline-md": ["var(--font-geist-sans)"],
        "headline-sm": ["var(--font-geist-sans)"],
        "body-lg": ["var(--font-geist-sans)"],
        "body-md": ["var(--font-geist-sans)"],
        "label-md": ["var(--font-geist-sans)"],
        "label-sm": ["var(--font-geist-sans)"],
      },
      fontSize: {
        "display-hero": ["56px", { lineHeight: "64px", letterSpacing: "-0.03em", fontWeight: "600" }],
        "display-hero-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-md": ["22px", { lineHeight: "30px", letterSpacing: "-0.015em", fontWeight: "500" }],
        "headline-sm": ["18px", { lineHeight: "26px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "body-lg": ["16px", { lineHeight: "26px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "22px", letterSpacing: "0em", fontWeight: "400" }],
        "label-md": ["13px", { lineHeight: "18px", letterSpacing: "0.01em", fontWeight: "500" }],
        "label-sm": ["11px", { lineHeight: "16px", letterSpacing: "0.03em", fontWeight: "500" }],
        code: ["13px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
      },
      boxShadow: {
        card: "0 1px 8px rgba(0,0,0,0.04)",
        pop: "0 12px 32px rgba(30,50,223,0.12)",
      },
    },
  },
  plugins: [],
};

export default config;
